= 0.Neovim必了解概念

在正式开始之前，有一些重要概念以及基础知识需要学习。**一定要先读完本篇再看后续篇幅！**

IMPORTANT: Neovim本身是一个Vim的分支，但后来Neovim逐渐引入了不少新特性。虽然如此，它还是保留着大量Vim的特性。 +
本文档不需要你有Vim基础，你完全可以直接上手Neovim以及本文档。但一定要记住这一点。



== 0.1.Neovim配置文件

Neovim的配置文件一般存放在以下目录：
* Linux/MacOS: `~/.config/nvim`
* Windows: `~/AppData/Local/nvim`

TIP: `~` 是当前用户的**家目录**。在Linux中一般是 `/home/用户名` ，在MacOS中一般是 `/Users/用户名` ，在Windows中一般是 `C:/Users/用户名` 。

Neovim的配置文件格式比较自由。在配置文件下需要一个 `init.lua` 或 `init.vim` 作为配置入口。
既然你都用Neovim了，那当然就要拥抱Neovim带来的Lua支持了，所以本文档[.underline]#只包含使用Lua进行配置的详解#。

NOTE: `.vim` 格式的配置文件是Vim的原生配置文件，Neovim也保留了它，但同时引入了完整的Lua支持，且比 `.vim` 更强大。 +
总之，在使用Neovim时，把 `.vim` 忘掉吧。Lua才是Neovim主场。~除非你是从Vim迁移过来的~

NOTE: 当 `init.lua` 和 `init.vim` 同时存在时，Neovim默认会忽略掉 `init.vim` ，~__以及没人会同时用这俩对吧__~

Neovim会在启动时运行 `init.lua` 。一般情况下，我们都只在 `init.lua` 里添加 `require` 语句引用其他配置文件（以及一些特殊的玩意），而不是直接将配置放在这里面。
除 `init.lua` 以外，Lua配置文件一般都存放在 `./lua` 目录里。

在使用 `require` 语句时，括号内可以__“使用 `.` 代替 `/` ”__，且无需添加文件扩展名。
同时，可以直接忽略 `./lua` 目录，Neovim会自动在该目录里寻找配置文件，不需要加上 `lua.` 。

文件树大概长这样：

 .config/nvim
 │
 ├─lua
 │ ├─plugins
 │ │ ├─plugin1.lua
 │ │ └─plugin2.lua
 │ ├─config
 │ │ ├─something.lua
 │ │ └─someotherthing.lua
 │ └─(your_own_config)
 └─init.lua

例如，想要引用 `./lua/plugins/plugin1.lua` ，就可以直接使用 `require(plugins.plugin1)` ，省略了路径中的父文件夹 `lua/` 和文件后缀 `.lua` 。

除了 `init.lua` （和 `./lua` ）以外，所有的配置都是完全自由的（只要你引用对了）。比如，你可以自由创建文件/夹，自由命名它们，以及自由修改内容。
但是注意，**要保持你自己的配置风格**，否则配置文件管理起来就会特别麻烦。你自己的配置风格由你自己决定，但一旦确定了就要严格遵循。
否则你就是故意给自己找麻烦。~[.line-through]#除非你是大懒虫#~



== 0.2.模式

模式同样是Vim继承下来的产物，但这种说法似乎并不太合适，因为Neovim本来就完全保留了Vim的使用模式。

模式，是指你当前的控制模式。常见的模式有以下几种：

* NORMAL
* INSERT
* COMMAND
* VISUAL

**NORMAL**，顾名思义，是常规控制光标位置的模式。在没有操作的情况下，Neovim一启动就会进入NORMAL模式。 +
在NORMAL模式下，可以通过各种操作移动光标位置，这里就不细讲了，会在 [.underline]#1.常用操作# 一篇中详解。

**INSERT**，即“插入模式”，你可以理解为更改文件内容的模式。在INSERT模式下可以自由地更改文件内容，按下ESC键可以退出。 +
进入INSERT模式的方法有多种，比如按下I键就是标准的INSERT模式，而按下A键进入的INSERT模式的光标位置会有所不同。这些都会在  [.underline]#1.常用操作# 一篇中详解。

**COMMAND**，命令模式，用于输入控制命令。按下:键可以进入(记得还要按Shift)。不少操作都会在该模式下完成。按下ESC键可以退出，按下Enter键执行命令。 +
依旧会在 [.underline]#1.常用操作# 一篇中详解。

**VISUAL**，选择模式。该模式可以选择一部分文本并对它们进行部分操作，比如删除。按下V键即可在当前光标位置进入该模式。
还是会在 [.underline]#1.常用操作# 一篇中详解。

除了这几种常见模式外，还有一些并不是很常见的模式。且插件/配置文件可以创建新模式，例如插件 `toggleterm.nvim` 添加的TERMINAL模式。
总之会在 [.underline]#1.常用操作# 一篇中详解。

模式这个概念特别重要，不把它搞懂你就完全无法使用Neovim。我相信你也可以搞懂。



== 0.3.缓冲区、窗口、标签页



